# Config file for automatic testing at travis-ci.org

# This reportedly works around an issue downloading packages from pypi on
# travis.  Consider removing this after the underlying issue is fixed.
# https://github.com/travis-ci/travis-ci/issues/2389
# sudo: false

dist: bionic

language: python
cache: pip
python:
  - '3.5'
  - '3.6'
  - '3.7'
  - '3.8-dev'

# command to install dependencies
install:
  - pip install --upgrade pip codecov
  - pip install --upgrade -e .[develop]
  - python3 setup.py build

# command to run tests
script:
  - pytest

after_success:
  - codecov

notifications:
  email:
    on_success: never
    on_failure: always